import React, {useCallback, useEffect, useRef, useState} from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import {Tooltip} from '@omars-lab/blog-ui';
import kanbanData from './kanban-data.json';
import {ideaTagTooltip} from '../../lib/idea-tags';
import type {BoardConfig, BoardId, KanbanCard, KanbanCardDetail, KanbanData} from './types';
import styles from './KanbanBoard.module.css';

/**
 * KanbanBoard — an interactive board that indexes TEMPORAL posts (experiments, ideas) as
 * cards, generated from post frontmatter. A card is one post; clicking it opens a modal
 * (the shared CustomEvent+host pattern from @omars-lab/blog-ui Question) with a link to the
 * full post. The board is parameterized by `board` so the same component renders the
 * Experimentation board and the Ideas board from one data file.
 *
 *   <KanbanBoard board="experiments" />
 *
 * DATA: src/components/KanbanBoard/kanban-data.json, generated by
 * scripts/generate-kanban-data.js (npm run generate-assets) from blog frontmatter. Moving a
 * card = changing a post's `stage` frontmatter; the board re-derives on the next build.
 * The modal host (<KanbanModalHost/>) is mounted once in src/theme/Root.tsx.
 */

// Per-board UI config: the ordered columns + their human labels/emoji. The column IDS must
// match the generator's BOARDS[...].columns (scripts/generate-kanban-data.js) — that file
// is the source of truth for which stage maps to which column.
const BOARD_CONFIG: Record<BoardId, BoardConfig> = {
  experiments: {
    title: 'Experimentation board',
    columns: [
      {id: 'proposed', label: 'Proposed', emoji: '💡'},
      {id: 'designed', label: 'Designed', emoji: '✏️'},
      {id: 'running', label: 'Running', emoji: '🟢'},
      {id: 'analyzing', label: 'Analyzing', emoji: '🔬'},
      {id: 'concluded', label: 'Concluded', emoji: '✅'},
    ],
  },
  ideas: {
    title: 'Ideas & initiatives board',
    columns: [
      {id: 'backlog', label: 'Backlog', emoji: '🗒️'},
      {id: 'exploring', label: 'Exploring', emoji: '🔎'},
      {id: 'building', label: 'Building', emoji: '🛠️'},
      {id: 'shipped', label: 'Shipped', emoji: '🚀'},
    ],
  },
  research: {
    title: 'Research board',
    columns: [
      {id: 'backlog', label: 'Backlog', emoji: '🗒️'},
      {id: 'researching', label: 'Researching', emoji: '🔬'},
      {id: 'learned', label: 'Learned', emoji: '🎓'},
    ],
  },
};

// Kind → emoji, for the badge on each card. Source of truth is scripts/lib/blog-kinds.json;
// only the board-relevant kinds are mirrored here (the component is independent of the
// build script's file tree). Keep in lockstep if a board-relevant kind's emoji changes.
const KIND_EMOJI: Record<string, string> = {
  'experiment-plan': '📝',
  'experiment-result': '📊',
  reflection: '💭',
  'design-story': '📐',
  'system-design': '🏗️',
  research: '🔬',
};

const PRIORITY_LABEL: Record<string, string> = {
  core: 'Core',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
};

// Card CLASSIFICATION → {emoji, label} for the class badge. A class groups a subset of a board's
// cards by what KIND of thing they are (e.g. the "first-time / new things" ideas), without being a
// card itself. An unknown class falls back to its raw value, title-cased.
const CLASS_META: Record<string, {emoji: string; label: string}> = {
  'first-time': {emoji: '🌱', label: 'First-time'},
};
function classMeta(cls: string): {emoji: string; label: string} {
  return CLASS_META[cls] || {emoji: '', label: cls.charAt(0).toUpperCase() + cls.slice(1).replace(/-/g, ' ')};
}

const DATA = kanbanData as KanbanData;

/* ── Card → modal CustomEvent (mirrors Question's openQuestionModal) ──────── */

export const KANBAN_MODAL_EVENT = 'bop:kanban-card-modal';

export function openKanbanCardModal(detail: KanbanCardDetail): void {
  if (typeof window === 'undefined') return;
  window.dispatchEvent(new CustomEvent(KANBAN_MODAL_EVENT, {detail}));
}

/* ── Card ─────────────────────────────────────────────────────────────────── */

interface CardProps {
  card: KanbanCard;
  columnLabel: string;
}

function Card({card, columnLabel}: CardProps): React.JSX.Element {
  const emoji = KIND_EMOJI[card.kind] || '';
  const priorityLabel = PRIORITY_LABEL[card.priority] || card.priority;

  const open = useCallback(() => {
    openKanbanCardModal({
      title: card.title,
      summary: card.summary,
      permalink: card.permalink,
      stage: card.stage,
      priority: card.priority,
      kind: card.kind,
      date: card.date,
      columnLabel,
    });
  }, [card, columnLabel]);

  const onKey = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        open();
      }
    },
    [open],
  );

  return (
    <button
      type="button"
      className={styles.card}
      onClick={open}
      onKeyDown={onKey}
      aria-haspopup="dialog">
      <span className={styles.cardTitle}>
        {emoji && (
          <span className={styles.cardKind} aria-hidden="true">
            {emoji}{' '}
          </span>
        )}
        {card.title}
      </span>
      {card.summary && <span className={styles.cardSummary}>{card.summary}</span>}
      {card.tags && card.tags.length > 0 && (
        <span className={styles.cardTags}>
          {card.tags.map((tag) => (
            // On the card the chip is inside the card <button>, so it can't host a focusable
            // Tooltip (no interactive-in-button); a native title gives the same explanation on
            // hover. The rich custom tooltip lives on the filter-bar chips below.
            <span key={tag} className={styles.tagChip} title={ideaTagTooltip(tag)}>
              {tag}
            </span>
          ))}
        </span>
      )}
      <span className={styles.cardMeta}>
        {card.class && (
          <span className={styles.classBadge}>
            {classMeta(card.class).emoji && (
              <span aria-hidden="true">{classMeta(card.class).emoji} </span>
            )}
            {classMeta(card.class).label}
          </span>
        )}
        {card.priority && (
          <span className={clsx(styles.pill, styles[`priority_${card.priority}`])}>
            {priorityLabel}
          </span>
        )}
        {card.date && <span className={styles.cardDate}>{card.date}</span>}
      </span>
    </button>
  );
}

/* ── Board ────────────────────────────────────────────────────────────────── */

export interface KanbanBoardProps {
  board: BoardId;
  /** Optional override of the board title heading. */
  title?: string;
}

export default function KanbanBoard({board, title}: KanbanBoardProps): React.JSX.Element {
  const config = BOARD_CONFIG[board];
  const allCards = (DATA[board] || []) as KanbanCard[];

  // Active tag filter (null = show all). Clicking a tag in the bar narrows the board to the
  // cards carrying that theme; clicking it again (or "All") clears the filter.
  const [activeTag, setActiveTag] = useState<string | null>(null);

  if (!config) {
    return <p className={styles.empty}>Unknown board: {board}</p>;
  }

  // The distinct theme tags across the board, with how many cards carry each — drives the
  // filter bar. Sorted by frequency (most common first), then alphabetically for stability.
  const tagCounts = new Map<string, number>();
  for (const card of allCards) {
    for (const tag of card.tags || []) tagCounts.set(tag, (tagCounts.get(tag) || 0) + 1);
  }
  const tags = [...tagCounts.entries()].sort(
    (a, b) => b[1] - a[1] || a[0].localeCompare(b[0]),
  );

  // Apply the active tag filter (if any) before grouping into columns.
  const cards =
    activeTag == null
      ? allCards
      : allCards.filter((c) => (c.tags || []).includes(activeTag));

  // Group cards by their resolved column id.
  const byColumn: Record<string, KanbanCard[]> = {};
  for (const col of config.columns) byColumn[col.id] = [];
  for (const card of cards) {
    (byColumn[card.stage] || byColumn[config.columns[0].id]).push(card);
  }

  const total = cards.length;

  // The columns scroll horizontally on narrow screens. On a phone the leading columns are
  // often empty (Proposed/Designed) while the action is mid-board (Running), so a mobile
  // user would land on an empty column and think the board is empty. On mount, scroll the
  // track so the FIRST POPULATED column is in view — without scrolling the page itself.
  const trackRef = useRef<HTMLDivElement>(null);
  const firstPopulatedRef = useRef<HTMLDivElement>(null);
  const firstPopulatedColId = config.columns.find((c) => (byColumn[c.id] || []).length > 0)?.id;
  useEffect(() => {
    const track = trackRef.current;
    const target = firstPopulatedRef.current;
    if (!track || !target) return;
    // Only act when the track actually overflows (mobile/narrow) and the target is off-screen.
    if (track.scrollWidth <= track.clientWidth) return;
    const left = target.offsetLeft - track.offsetLeft;
    track.scrollTo({left, behavior: 'auto'});
  }, [firstPopulatedColId, activeTag]);

  return (
    <section className={styles.board} aria-label={title || config.title}>
      {tags.length > 0 && (
        <div className={styles.filterBar} role="group" aria-label="Filter by tag">
          <button
            type="button"
            className={clsx(styles.filterChip, activeTag == null && styles.filterChipActive)}
            aria-pressed={activeTag == null}
            onClick={() => setActiveTag(null)}>
            All <span className={styles.filterCount}>{allCards.length}</span>
          </button>
          {tags.map(([tag, count]) => {
            const isActive = activeTag === tag;
            return (
              // Each filter chip gets a custom hover/focus/tap tooltip explaining the tag (a
              // terse slug like "sge" / "automa" means little on its own). The Tooltip wraps
              // the button (span > button — valid; the chip is the only interactive child).
              <Tooltip
                key={tag}
                content={
                  <>
                    <b>{tag}</b>
                    <br />
                    {ideaTagTooltip(tag)}
                  </>
                }>
                <button
                  type="button"
                  className={clsx(styles.filterChip, isActive && styles.filterChipActive)}
                  aria-pressed={isActive}
                  onClick={() => setActiveTag(isActive ? null : tag)}>
                  {tag} <span className={styles.filterCount}>{count}</span>
                </button>
              </Tooltip>
            );
          })}
        </div>
      )}
      <div className={styles.columns} role="list" ref={trackRef}>
        {config.columns.map((col) => {
          const colCards = byColumn[col.id] || [];
          const isFirstPopulated = col.id === firstPopulatedColId;
          return (
            <div
              key={col.id}
              className={styles.column}
              role="listitem"
              ref={isFirstPopulated ? firstPopulatedRef : undefined}>
              <div className={styles.columnHeader}>
                <span className={styles.columnLabel}>
                  {col.emoji && <span aria-hidden="true">{col.emoji} </span>}
                  {col.label}
                </span>
                <span className={styles.columnCount} aria-label={`${colCards.length} cards`}>
                  {colCards.length}
                </span>
              </div>
              <div className={styles.columnBody}>
                {colCards.map((card) => (
                  <Card key={card.slug} card={card} columnLabel={col.label} />
                ))}
                {colCards.length === 0 && (
                  <p className={styles.columnEmpty}>Nothing here yet.</p>
                )}
              </div>
            </div>
          );
        })}
      </div>
      {total === 0 && activeTag == null && (
        <p className={styles.empty}>
          No posts on this board yet. Cards are generated from post frontmatter.
        </p>
      )}
      {total === 0 && activeTag != null && (
        <p className={styles.empty}>
          No cards tagged “{activeTag}”.{' '}
          <button type="button" className={styles.clearFilter} onClick={() => setActiveTag(null)}>
            Clear filter
          </button>
        </p>
      )}
    </section>
  );
}

/* ── Modal host (mount once in Root.tsx, next to QuestionModalHost) ────────── */

interface ModalState {
  open: boolean;
  detail: KanbanCardDetail | null;
}

function KanbanModalImpl(): React.JSX.Element | null {
  const [{open, detail}, setState] = useState<ModalState>({open: false, detail: null});
  const close = useCallback(() => setState((s) => ({...s, open: false})), []);

  useEffect(() => {
    const onOpen = (e: Event) => {
      const d = (e as CustomEvent<KanbanCardDetail>).detail;
      setState({open: true, detail: d});
    };
    window.addEventListener(KANBAN_MODAL_EVENT, onOpen as EventListener);
    return () => window.removeEventListener(KANBAN_MODAL_EVENT, onOpen as EventListener);
  }, []);

  useEffect(() => {
    if (!open) return undefined;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') close();
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, close]);

  if (!open || !detail) return null;

  const emoji = KIND_EMOJI[detail.kind] || '';
  const priorityLabel = PRIORITY_LABEL[detail.priority] || detail.priority;

  return (
    <div
      className={styles.overlay}
      role="dialog"
      aria-modal="true"
      aria-label="Card details"
      onClick={close}>
      <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
        <button type="button" className={styles.closeBtn} aria-label="Dismiss" onClick={close}>
          &times;
        </button>
        <p className={styles.modalTitle}>
          {emoji && <span aria-hidden="true">{emoji} </span>}
          {detail.title}
        </p>
        <span className={styles.modalBadges}>
          <span className={styles.pill}>{detail.columnLabel}</span>
          {detail.priority && (
            <span className={clsx(styles.pill, styles[`priority_${detail.priority}`])}>
              {priorityLabel}
            </span>
          )}
          {detail.date && <span className={styles.cardDate}>{detail.date}</span>}
        </span>
        {detail.summary && <p className={styles.modalSummary}>{detail.summary}</p>}
        <Link className={styles.modalLink} to={detail.permalink}>
          Read the full post &rsaquo;
        </Link>
      </div>
    </div>
  );
}

export function KanbanModalHost(): React.JSX.Element | null {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  if (!mounted) return null;
  return <KanbanModalImpl />;
}
