import React, {useCallback, useEffect, useState} from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import kanbanData from './kanban-data.json';
import type {BoardConfig, BoardId, KanbanCard, KanbanCardDetail, KanbanData} from './types';
import styles from './KanbanBoard.module.css';

/**
 * KanbanBoard — an interactive board that indexes TEMPORAL posts (experiments, ideas) as
 * cards, generated from post frontmatter. A card is one post; clicking it opens a modal
 * (the shared CustomEvent+host pattern from @omars-lab/blog-ui Question) with a link to the
 * full post. The board is parameterized by `board` so the same component renders the
 * Experimentation board and the Ideas board from one data file.
 *
 *   <KanbanBoard board="experiments" />
 *
 * DATA: src/components/KanbanBoard/kanban-data.json, generated by
 * scripts/generate-kanban-data.js (npm run generate-assets) from blog frontmatter. Moving a
 * card = changing a post's `stage` frontmatter; the board re-derives on the next build.
 * The modal host (<KanbanModalHost/>) is mounted once in src/theme/Root.tsx.
 */

// Per-board UI config: the ordered columns + their human labels/emoji. The column IDS must
// match the generator's BOARDS[...].columns (scripts/generate-kanban-data.js) — that file
// is the source of truth for which stage maps to which column.
const BOARD_CONFIG: Record<BoardId, BoardConfig> = {
  experiments: {
    title: 'Experimentation board',
    columns: [
      {id: 'proposed', label: 'Proposed', emoji: '💡'},
      {id: 'designed', label: 'Designed', emoji: '✏️'},
      {id: 'running', label: 'Running', emoji: '🟢'},
      {id: 'analyzing', label: 'Analyzing', emoji: '🔬'},
      {id: 'concluded', label: 'Concluded', emoji: '✅'},
    ],
  },
  ideas: {
    title: 'Ideas & initiatives board',
    columns: [
      {id: 'backlog', label: 'Backlog', emoji: '🗒️'},
      {id: 'exploring', label: 'Exploring', emoji: '🔎'},
      {id: 'building', label: 'Building', emoji: '🛠️'},
      {id: 'shipped', label: 'Shipped', emoji: '🚀'},
    ],
  },
};

// Kind → emoji, for the badge on each card. Source of truth is scripts/lib/blog-kinds.json;
// only the board-relevant kinds are mirrored here (the component is independent of the
// build script's file tree). Keep in lockstep if a board-relevant kind's emoji changes.
const KIND_EMOJI: Record<string, string> = {
  'experiment-plan': '📝',
  'experiment-result': '📊',
  reflection: '💭',
  'design-story': '📐',
  'system-design': '🏗️',
};

const PRIORITY_LABEL: Record<string, string> = {
  core: 'Core',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
};

const DATA = kanbanData as KanbanData;

/* ── Card → modal CustomEvent (mirrors Question's openQuestionModal) ──────── */

export const KANBAN_MODAL_EVENT = 'bop:kanban-card-modal';

export function openKanbanCardModal(detail: KanbanCardDetail): void {
  if (typeof window === 'undefined') return;
  window.dispatchEvent(new CustomEvent(KANBAN_MODAL_EVENT, {detail}));
}

/* ── Card ─────────────────────────────────────────────────────────────────── */

interface CardProps {
  card: KanbanCard;
  columnLabel: string;
}

function Card({card, columnLabel}: CardProps): React.JSX.Element {
  const emoji = KIND_EMOJI[card.kind] || '';
  const priorityLabel = PRIORITY_LABEL[card.priority] || card.priority;

  const open = useCallback(() => {
    openKanbanCardModal({
      title: card.title,
      summary: card.summary,
      permalink: card.permalink,
      stage: card.stage,
      priority: card.priority,
      kind: card.kind,
      date: card.date,
      columnLabel,
    });
  }, [card, columnLabel]);

  const onKey = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        open();
      }
    },
    [open],
  );

  return (
    <button
      type="button"
      className={styles.card}
      onClick={open}
      onKeyDown={onKey}
      aria-haspopup="dialog">
      <span className={styles.cardTitle}>
        {emoji && (
          <span className={styles.cardKind} aria-hidden="true">
            {emoji}{' '}
          </span>
        )}
        {card.title}
      </span>
      {card.summary && <span className={styles.cardSummary}>{card.summary}</span>}
      <span className={styles.cardMeta}>
        {card.priority && (
          <span className={clsx(styles.pill, styles[`priority_${card.priority}`])}>
            {priorityLabel}
          </span>
        )}
        {card.date && <span className={styles.cardDate}>{card.date}</span>}
      </span>
    </button>
  );
}

/* ── Board ────────────────────────────────────────────────────────────────── */

export interface KanbanBoardProps {
  board: BoardId;
  /** Optional override of the board title heading. */
  title?: string;
}

export default function KanbanBoard({board, title}: KanbanBoardProps): React.JSX.Element {
  const config = BOARD_CONFIG[board];
  const cards = (DATA[board] || []) as KanbanCard[];

  if (!config) {
    return <p className={styles.empty}>Unknown board: {board}</p>;
  }

  // Group cards by their resolved column id.
  const byColumn: Record<string, KanbanCard[]> = {};
  for (const col of config.columns) byColumn[col.id] = [];
  for (const card of cards) {
    (byColumn[card.stage] || byColumn[config.columns[0].id]).push(card);
  }

  const total = cards.length;

  return (
    <section className={styles.board} aria-label={title || config.title}>
      <div className={styles.columns} role="list">
        {config.columns.map((col) => {
          const colCards = byColumn[col.id] || [];
          return (
            <div key={col.id} className={styles.column} role="listitem">
              <div className={styles.columnHeader}>
                <span className={styles.columnLabel}>
                  {col.emoji && <span aria-hidden="true">{col.emoji} </span>}
                  {col.label}
                </span>
                <span className={styles.columnCount} aria-label={`${colCards.length} cards`}>
                  {colCards.length}
                </span>
              </div>
              <div className={styles.columnBody}>
                {colCards.map((card) => (
                  <Card key={card.slug} card={card} columnLabel={col.label} />
                ))}
                {colCards.length === 0 && (
                  <p className={styles.columnEmpty}>Nothing here yet.</p>
                )}
              </div>
            </div>
          );
        })}
      </div>
      {total === 0 && (
        <p className={styles.empty}>
          No posts on this board yet. Cards are generated from post frontmatter.
        </p>
      )}
    </section>
  );
}

/* ── Modal host (mount once in Root.tsx, next to QuestionModalHost) ────────── */

interface ModalState {
  open: boolean;
  detail: KanbanCardDetail | null;
}

function KanbanModalImpl(): React.JSX.Element | null {
  const [{open, detail}, setState] = useState<ModalState>({open: false, detail: null});
  const close = useCallback(() => setState((s) => ({...s, open: false})), []);

  useEffect(() => {
    const onOpen = (e: Event) => {
      const d = (e as CustomEvent<KanbanCardDetail>).detail;
      setState({open: true, detail: d});
    };
    window.addEventListener(KANBAN_MODAL_EVENT, onOpen as EventListener);
    return () => window.removeEventListener(KANBAN_MODAL_EVENT, onOpen as EventListener);
  }, []);

  useEffect(() => {
    if (!open) return undefined;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') close();
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, close]);

  if (!open || !detail) return null;

  const emoji = KIND_EMOJI[detail.kind] || '';
  const priorityLabel = PRIORITY_LABEL[detail.priority] || detail.priority;

  return (
    <div
      className={styles.overlay}
      role="dialog"
      aria-modal="true"
      aria-label="Card details"
      onClick={close}>
      <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
        <button type="button" className={styles.closeBtn} aria-label="Dismiss" onClick={close}>
          &times;
        </button>
        <p className={styles.modalTitle}>
          {emoji && <span aria-hidden="true">{emoji} </span>}
          {detail.title}
        </p>
        <span className={styles.modalBadges}>
          <span className={styles.pill}>{detail.columnLabel}</span>
          {detail.priority && (
            <span className={clsx(styles.pill, styles[`priority_${detail.priority}`])}>
              {priorityLabel}
            </span>
          )}
          {detail.date && <span className={styles.cardDate}>{detail.date}</span>}
        </span>
        {detail.summary && <p className={styles.modalSummary}>{detail.summary}</p>}
        <Link className={styles.modalLink} to={detail.permalink}>
          Read the full post &rsaquo;
        </Link>
      </div>
    </div>
  );
}

export function KanbanModalHost(): React.JSX.Element | null {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  if (!mounted) return null;
  return <KanbanModalImpl />;
}
