import type {Meta, StoryObj} from '@storybook/react';
import KanbanBoard, {KanbanModalHost} from './index';

/**
 * KanbanBoard renders the cards from the generated kanban-data.json (built from blog
 * frontmatter by scripts/generate-kanban-data.js). The stories show the two boards; the
 * modal host is included so clicking a card opens the detail modal in Storybook too.
 */
const meta = {
  title: 'Components/KanbanBoard',
  component: KanbanBoard,
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'An interactive board that indexes temporal posts (experiments, ideas) as cards ' +
          'generated from post frontmatter. Clicking a card opens a modal with a link to the ' +
          'full post. Parameterized by `board` (experiments | ideas). Cards come from ' +
          'kanban-data.json (regenerated by `npm run generate-assets`).',
      },
    },
  },
  tags: ['autodocs'],
  argTypes: {
    board: {
      control: 'select',
      options: ['experiments', 'ideas'],
      description: 'Which board to render (selects the data slice + columns).',
    },
    title: {control: 'text', description: 'Optional override of the board title.'},
  },
  decorators: [
    (Story) => (
      <div style={{padding: '1.5rem'}}>
        <Story />
        <KanbanModalHost />
      </div>
    ),
  ],
} satisfies Meta<typeof KanbanBoard>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Experiments: Story = {
  args: {board: 'experiments'},
};

export const Ideas: Story = {
  args: {board: 'ideas'},
};
