#!/bin/bash
# PreToolUse hook for Edit|Write: BLOCK (exit 2) edits to autogenerated / build-derived
# files. These are regenerated by `npm run generate-assets` (prebuild/prestart) or by
# Docusaurus/Storybook — any hand-edit is silently lost on the next build. The fix is to
# edit the GENERATOR or the frontmatter SOURCE, never the generated output (CLAUDE.md
# tenet: fail closed — the unsafe path should be impossible by omission).
#
# Two carve-outs this hook is careful about:
#   • Secrets (.env / *.token) are NOT in scope here — they are gitignored for a different
#     reason and handled by the secret model; editing .env locally is legitimate.
#   • designs/_rosette-zeros-variants.js is COMMITTED SOURCE (raw output of the private
#     bikar CLI, not regenerable at build) — it is the gitignored-adjacent EXCEPTION and
#     must NOT be blocked. (Its sibling _binary-pyramid-variants.js IS generated → blocked.)
#
# Blocking taxonomy:
#   GENERATED OUTPUTS (regenerated by generate-assets):
#     src/components/Changelog/changelog-data.json
#     src/components/Vote/ideas-data.json
#     src/components/KanbanBoard/kanban-data.json
#     designs/_binary-pyramid-variants.js
#   DERIVED DIRECTORIES (Docusaurus/Storybook/build copy output):
#     build/ (and build-*), .docusaurus/, node_modules/, static/storybook/,
#     storybook-static/, src/pages/changelog/, static/premium/
#
# Exit 2 = block + feed stderr back to the model so it self-corrects to the source.

input=$(cat)
file_path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')
[ -n "$file_path" ] || exit 0

# Normalize: we match on path SUFFIXES so absolute or relative paths both work.
block() {
  rel="${file_path##*/bytesofpurpose-blog/}"
  {
    echo "🛑 Refusing to edit a GENERATED / build-derived file: '$rel'"
    echo "   Reason: $1"
    echo "   This file is overwritten on the next build (npm run generate-assets /"
    echo "   yarn build / storybook build) — a hand-edit here is silently lost."
    echo "   ➡  Edit the GENERATOR or the frontmatter SOURCE instead, then run"
    echo "      \`make generate-assets\` (or rebuild). See the build-system design post."
  } >&2
  exit 2
}

# --- EXCEPTION first: committed source that lives next to generated output ---
case "$file_path" in
  */designs/_rosette-zeros-variants.js) exit 0 ;;   # committed bikar-CLI source, not regenerable
esac

# --- Generated data outputs (regenerated by generate-assets) ---
case "$file_path" in
  */bytesofpurpose-blog/src/components/Changelog/changelog-data.json)
    block "regenerated by scripts/generate-changelog-data.js (edit changelog/ source)";;
  */bytesofpurpose-blog/src/components/Vote/ideas-data.json)
    block "regenerated by scripts/generate-ideas-data.js (edit the idea posts' frontmatter)";;
  */bytesofpurpose-blog/src/components/KanbanBoard/kanban-data.json)
    block "regenerated by scripts/generate-kanban-data.js (edit the posts' stage/priority frontmatter)";;
  */bytesofpurpose-blog/designs/_binary-pyramid-variants.js)
    block "regenerated by scripts/generate-logo-variants-data.js (edit src/lib/binary-pyramid-logo.js)";;
esac

# --- Build-derived directories (never source) ---
case "$file_path" in
  */bytesofpurpose-blog/build/*|*/bytesofpurpose-blog/build-*/*)
    block "Docusaurus production build output (build/)";;
  */bytesofpurpose-blog/.docusaurus/*)
    block "Docusaurus generated cache (.docusaurus/)";;
  */bytesofpurpose-blog/static/storybook/*|*/bytesofpurpose-blog/storybook-static/*)
    block "Storybook build output (static/storybook/)";;
  */bytesofpurpose-blog/src/pages/changelog/*)
    block "generated changelog pages (copied from changelog/ at build)";;
  */bytesofpurpose-blog/static/premium/*)
    block "encrypted premium sidecars (regenerated by rehype-premium-encrypt at build)";;
  */node_modules/*)
    block "installed dependency (node_modules/)";;
esac

# Not a generated/derived path → allow.
exit 0
