import React from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import projectsData from './projects-data.json';
import styles from './ProjectsCatalog.module.css';

/**
 * ProjectsCatalog — the durable Projects hub at /craft/software-development/projects.
 *
 * Renders projects-data.json (generated by scripts/generate-projects-data.js via
 * `npm run generate-assets`), which groups the /initiatives project LOGS by their
 * `project_area:` frontmatter (frontend | backend | script | other). The catalog is the
 * durable index; each dated log lives on the /initiatives blog. It can never drift from
 * the posts because it is generated PER POST — a project moves area by editing that post's
 * `project_area`, not this component.
 *
 * DRAFT posts are shown (so the hub reflects work in progress) but NOT linked: a link to a
 * draft 404s in the prod build. A draft renders as a muted row with an "in progress" badge.
 */

interface Project {
  slug: string;
  title: string;
  description: string;
  permalink: string;
  date: string;
  draft: boolean;
  tags: string[];
}
type ProjectsData = Record<string, Project[]>;

const DATA = projectsData as ProjectsData;

// Reader-facing labels + order for the areas. Keys must match AREAS in the generator.
const AREA_META: {key: string; label: string; blurb: string}[] = [
  {key: 'frontend', label: 'Frontend', blurb: 'Sites, apps, and visual tools I built.'},
  {key: 'backend', label: 'Backend', blurb: 'Services, infrastructure, and automation that runs behind the scenes.'},
  {key: 'script', label: 'Scripting', blurb: 'Command-line tools and scripts that automate the small things.'},
  {key: 'other', label: 'Other', blurb: 'Projects that do not fit a single area.'},
];

function ProjectCard({project}: {project: Project}): React.JSX.Element {
  const body = (
    <>
      <span className={styles.cardTitle}>{project.title}</span>
      {project.description && <span className={styles.cardDesc}>{project.description}</span>}
      <span className={styles.cardMeta}>
        {project.draft && <span className={styles.draftBadge}>in progress</span>}
        {project.date && <span className={styles.date}>{project.date}</span>}
      </span>
    </>
  );

  // A draft has no published URL — render it as a non-linked, muted card.
  if (project.draft) {
    return <li className={clsx(styles.card, styles.cardDraft)}>{body}</li>;
  }
  return (
    <li className={styles.card}>
      <Link className={styles.cardLink} to={project.permalink}>
        {body}
      </Link>
    </li>
  );
}

export default function ProjectsCatalog(): React.JSX.Element {
  const areas = AREA_META.filter((a) => (DATA[a.key] || []).length > 0);

  if (areas.length === 0) {
    return <p className={styles.empty}>No projects catalogued yet.</p>;
  }

  return (
    <div className={styles.catalog}>
      {areas.map((area) => {
        const projects = DATA[area.key] || [];
        return (
          <section key={area.key} className={styles.area}>
            <h2 className={styles.areaTitle}>
              {area.label}
              <span className={styles.areaCount}>{projects.length}</span>
            </h2>
            <p className={styles.areaBlurb}>{area.blurb}</p>
            <ul className={styles.grid}>
              {projects.map((p) => (
                <ProjectCard key={p.slug} project={p} />
              ))}
            </ul>
          </section>
        );
      })}
    </div>
  );
}
