/**
 * Sidebar for the 🔄 Habits docs instance (id: 'habits', routeBasePath: /habits).
 * Autogenerated from docs/habits/ — this sidebar contains ONLY the habits groups (professional /
 * personal / spiritual). Its own instance, so it never mixes with Craft/Journey.
 */
module.exports = {
  habitsSidebar: [{type: 'autogenerated', dirName: '.'}],
};
