/**
 * Sidebar for the 🧭 Legend docs instance (id: 'legend', routeBasePath: /legend).
 * Autogenerated from docs/legend/ — the map for the whole site: the durable/temporal
 * explainer + post-kind emoji, the glossary, and all the terminology pages. Its own
 * instance + sidebar, like Craft/Journey, so the two never mix.
 */
module.exports = {
  legendSidebar: [{type: 'autogenerated', dirName: '.'}],
};
