/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // Two-tier docs IA: "Craft" (professional topics) and "Self" (personal topics),
  // each its own navbar item + sidebar. Welcome appears first in BOTH as the shared
  // entry point. Each parent autogenerates its topics from docs/<parent>/ ordered by
  // the topics' _category_.json `position`. See the Craft/Self split plan.
  craftSidebar: [
    'welcome/README',
    {type: 'autogenerated', dirName: 'craft'},
  ],
  selfSidebar: [
    'welcome/README',
    {type: 'autogenerated', dirName: 'self'},
  ],

  // Changelog sidebar - autogenerated from changelog directory
  // This allows the changelog docs plugin to discover and serve all changelog entries
  changelogSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from changelog root directory
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
