/**
 * Sidebar for the 🪞 Self docs instance (id: 'self', routeBasePath: /self).
 * Autogenerated from docs/self/ — this sidebar contains ONLY self topics (faith,
 * personal growth). Craft is a separate instance with its own sidebar.
 */
module.exports = {
  selfSidebar: [{type: 'autogenerated', dirName: '.'}],
};
