/**
 * Sidebar for the 🪞 Journey docs instance (plugin id: 'self', routeBasePath: /journey).
 * Autogenerated from docs/journey/ — this sidebar contains ONLY journey topics (faith,
 * personal growth). Craft is a separate instance with its own sidebar.
 */
module.exports = {
  selfSidebar: [{type: 'autogenerated', dirName: '.'}],
};
