/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // Two-tier docs IA: "Craft" (outrospective — professional topics) and "Self"
  // (introspective — personal topics), each its OWN navbar item + sidebar that shows
  // ONLY its own half. Each autogenerates from docs/<parent>/ (the parent README is the
  // section landing, ordered first), so clicking Craft never shows Self and vice-versa.
  // The shared welcome/ page (homepage CTA target) is intentionally NOT in either
  // sidebar — it routes readers INTO one half via its two CTAs. See the Craft/Self plan.
  craftSidebar: [
    {type: 'autogenerated', dirName: 'craft'},
  ],
  selfSidebar: [
    {type: 'autogenerated', dirName: 'self'},
  ],

  // Changelog sidebar - autogenerated from changelog directory
  // This allows the changelog docs plugin to discover and serve all changelog entries
  changelogSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from changelog root directory
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
