/**
 * Sidebar for the 🛠️ Craft docs instance (id: 'craft', routeBasePath: /craft).
 * Autogenerated from docs/craft/ — this sidebar contains ONLY craft topics. Self is a
 * separate instance with its own sidebar (sidebars-self.js), so the two never mix.
 */
module.exports = {
  craftSidebar: [{type: 'autogenerated', dirName: '.'}],
};
