import React from 'react';
import Link from '@docusaurus/Link';
import reposData from './repos-data.json';
import styles from './RepoCatalog.module.css';

/**
 * RepoCatalog — the "Repos of Interest" reference catalog on /craft workspace/tools.
 *
 * Renders repos-data.json (generated by scripts/generate-repos-data.js from the
 * hand-authored src/data/repos-of-interest.json), grouping each repository under EVERY
 * tag it carries (tool / relevant / genai / testing / ...). A repo is a catalog ENTRY
 * (name + url + blurb + tags), not a page, so this is a reference list, not an index of
 * posts. Add a repo by editing the source JSON and regenerating.
 *
 * A `tags` prop optionally filters to a subset of tags (e.g. <RepoCatalog tags={['tool']}/>).
 */

interface Repo {
  name: string;
  url: string;
  blurb: string;
  tags: string[];
}
interface Group {
  tag: string;
  gloss: string;
  repos: Repo[];
}
interface ReposData {
  tags: Record<string, string>;
  groups: Group[];
  all: Repo[];
}

const DATA = reposData as ReposData;

function RepoCard({repo}: {repo: Repo}): React.JSX.Element {
  return (
    <li className={styles.card}>
      <Link className={styles.cardLink} to={repo.url}>
        <span className={styles.cardName}>{repo.name}</span>
        <span className={styles.cardBlurb}>{repo.blurb}</span>
        <span className={styles.cardTags}>
          {repo.tags.map((t) => (
            <span key={t} className={styles.tag}>
              {t}
            </span>
          ))}
        </span>
      </Link>
    </li>
  );
}

export default function RepoCatalog({tags}: {tags?: string[]}): React.JSX.Element {
  const groups = DATA.groups.filter(
    (g) => g.repos.length > 0 && (!tags || tags.includes(g.tag)),
  );

  if (groups.length === 0) {
    return <p className={styles.empty}>No repositories catalogued yet.</p>;
  }

  return (
    <div className={styles.catalog}>
      {groups.map((group) => (
        <section key={group.tag} className={styles.group}>
          <h2 className={styles.groupTitle}>
            #{group.tag}
            <span className={styles.groupCount}>{group.repos.length}</span>
          </h2>
          {group.gloss && <p className={styles.groupGloss}>{group.gloss}</p>}
          <ul className={styles.grid}>
            {group.repos.map((r) => (
              <RepoCard key={r.url} repo={r} />
            ))}
          </ul>
        </section>
      ))}
    </div>
  );
}
