import type { ChangelogEntry } from './types';
// Import the generated JSON data file
// This file is generated by scripts/generate-changelog-data.js
import changelogData from './changelog-data.json';

/**
 * Get all changelog entries from the generated data file
 * The data file is generated at build time by scanning the changelog directory
 */
export function getAllChangelogEntries(): ChangelogEntry[] {
  return changelogData as ChangelogEntry[];
}

