import type { IdeaEntry } from './types';
// Import the generated JSON data file.
// This file is generated by scripts/generate-ideas-data.js (run via the
// prestart/prebuild npm hooks), mirroring the changelog data pipeline.
import ideasData from './ideas-data.json';

/**
 * Get all post-idea entries from the generated data file.
 * The data file is generated at build time by scanning the `ideas/` directory.
 */
export function getAllIdeas(): IdeaEntry[] {
  return ideasData as IdeaEntry[];
}
