import React from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import todosData from './todos-data.json';
import styles from './Todos.module.css';

/**
 * TodosDashboard — the /todos experience. Renders the consolidated todos dataset
 * (todos-data.json, generated by scripts/generate-todos-data.js via `npm run generate-assets`)
 * as a rollup PER POST: site-wide stat cards + one row per post with its task counts. The tasks
 * themselves live in the post (rendered by <TaskList>); this page is the index, not a task dump
 * (a flat list of every task is noise).
 */

interface PostRollup {
  title: string;
  permalink: string;
  open: number;
  done: number;
  scheduled: number;
  total: number;
  latestDue: string | null;
}
interface TodosData {
  totals: {open: number; done: number; total: number; scheduled: number; tracked: number; posts: number};
  posts: PostRollup[];
}

const DATA = todosData as TodosData;

function ageLabel(dateStr: string): string {
  const then = new Date(dateStr + 'T00:00:00');
  const now = new Date();
  const d = Math.floor((now.getTime() - then.getTime()) / 86_400_000);
  if (d < 0) return `in ${-d}d`;
  if (d === 0) return 'today';
  if (d < 60) return `${d}d ago`;
  if (d < 730) return `${Math.round(d / 30)}mo ago`;
  return `${Math.round(d / 365)}y ago`;
}

function Stat({n, label}: {n: number; label: string}): React.JSX.Element {
  return (
    <div className={styles.stat}>
      <div className={styles.statNum}>{n}</div>
      <div className={styles.statLabel}>{label}</div>
    </div>
  );
}

function PostRow({post}: {post: PostRollup}): React.JSX.Element {
  const cleared = post.open === 0;
  return (
    <li className={clsx(styles.post, cleared && styles.postCleared)}>
      <Link className={styles.postTitle} to={post.permalink}>
        {post.title}
      </Link>
      <span className={styles.counts}>
        {post.open > 0 && <span className={clsx(styles.badge, styles.badgeOpen)}>{post.open} open</span>}
        {post.scheduled > 0 && (
          <span className={clsx(styles.badge, styles.badgeSched)}>
            📅 {post.scheduled} scheduled
            {post.latestDue ? ` · ${ageLabel(post.latestDue)}` : ''}
          </span>
        )}
        {post.done > 0 && <span className={clsx(styles.badge, styles.badgeDone)}>{post.done} done</span>}
        {cleared && <span className={clsx(styles.badge, styles.badgeClear)}>✓ all done</span>}
      </span>
    </li>
  );
}

export default function TodosDashboard(): React.JSX.Element {
  const {totals, posts} = DATA;
  const active = posts.filter((p) => p.open > 0);
  const cleared = posts.filter((p) => p.open === 0);

  return (
    <div className={styles.todos}>
      <div className={styles.stats}>
        <Stat n={totals.open} label="open (all)" />
        <Stat n={totals.done} label="done (all)" />
        <Stat n={totals.posts} label="posts" />
        <Stat n={totals.scheduled} label="scheduled" />
      </div>
      <p className={styles.note}>
        {totals.total} markdown tasks across the site, rolled up by post. Only posts with tracked
        work (a schedule tag, a planning area, or a task list) are shown; open the post to see and
        check off its tasks.
      </p>

      <section>
        <h2 className={styles.sectionTitle}>Posts with open tasks ({active.length})</h2>
        <ul className={styles.list}>
          {active.map((p) => (
            <PostRow key={p.permalink} post={p} />
          ))}
        </ul>
      </section>

      {cleared.length > 0 && (
        <section>
          <h2 className={styles.sectionTitle}>Cleared ({cleared.length})</h2>
          <ul className={styles.list}>
            {cleared.map((p) => (
              <PostRow key={p.permalink} post={p} />
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}
