import React from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import todosData from './todos-data.json';
import styles from './Todos.module.css';

/**
 * TodosDashboard — the /todos experience. Renders the consolidated todos dataset
 * (todos-data.json, generated by scripts/generate-todos-data.js via `npm run generate-assets`)
 * as a rollup + a focused list of the genuinely-tracked todos across the site.
 *
 * The data is FOCUSED on purpose: ~1000 generic doc checklist items are counted in the totals
 * but not listed; only tracked work (a scheduling breadcrumb, a tracked PM area, or a <TaskList>)
 * is surfaced, so the page stays signal. "Age" is computed against the day the page loads (the
 * generator stays deterministic and does not bake in "days past due"). Most due dates are old
 * capture dates, so this frames them as AGE, not alarmist "overdue".
 */

interface TodoSource {
  title: string;
  permalink: string;
}
interface TodoItem {
  text: string;
  done: boolean;
  source: TodoSource;
  due: string | null;
  doneDate: string | null;
  recurrence: string | null;
  datestamps: string[];
  hashtags: string[];
}
interface TodosData {
  totals: {open: number; done: number; total: number; scheduled: number; tracked: number};
  items: TodoItem[];
}

const DATA = todosData as TodosData;

// Days between a YYYY-MM-DD and today (local). Positive = in the past.
function ageDays(dateStr: string): number {
  const then = new Date(dateStr + 'T00:00:00');
  const now = new Date();
  return Math.floor((now.getTime() - then.getTime()) / 86_400_000);
}

function ageLabel(dateStr: string): string {
  const d = ageDays(dateStr);
  if (d < 0) return `in ${-d}d`;
  if (d === 0) return 'today';
  if (d < 60) return `${d}d ago`;
  if (d < 730) return `${Math.round(d / 30)}mo ago`;
  return `${Math.round(d / 365)}y ago`;
}

function Stat({n, label}: {n: number; label: string}): React.JSX.Element {
  return (
    <div className={styles.stat}>
      <div className={styles.statNum}>{n}</div>
      <div className={styles.statLabel}>{label}</div>
    </div>
  );
}

function Row({item}: {item: TodoItem}): React.JSX.Element {
  return (
    <li className={clsx(styles.item, item.done && styles.itemDone)}>
      <span className={styles.checkbox} aria-hidden="true">
        {item.done ? '☑' : '☐'}
      </span>
      <span className={styles.text}>{item.text}</span>
      <span className={styles.meta}>
        {item.due && !item.done && (
          <span className={clsx(styles.chip, styles.chipDue)}>📅 scheduled {ageLabel(item.due)}</span>
        )}
        {item.recurrence && <span className={clsx(styles.chip, styles.chipRecur)}>🔁 {item.recurrence}</span>}
        {item.doneDate && <span className={clsx(styles.chip, styles.chipDone)}>✅ {item.doneDate}</span>}
        <Link className={styles.source} to={item.source.permalink}>
          {item.source.title}
        </Link>
      </span>
    </li>
  );
}

export default function TodosDashboard(): React.JSX.Element {
  const {totals, items} = DATA;
  const scheduled = items.filter((i) => i.due && !i.done);
  const openTracked = items.filter((i) => !i.done && !(i.due && !i.done));
  const done = items.filter((i) => i.done);

  return (
    <div className={styles.todos}>
      <div className={styles.stats}>
        <Stat n={totals.open} label="open (all)" />
        <Stat n={totals.done} label="done (all)" />
        <Stat n={totals.tracked} label="tracked" />
        <Stat n={totals.scheduled} label="scheduled" />
      </div>
      <p className={styles.note}>
        {totals.total} markdown tasks across the site; {totals.tracked} are tracked work (have a
        schedule tag, live in a planning area, or sit in a task list) and are listed below. The
        rest are generic checklists, counted but not shown.
      </p>

      {scheduled.length > 0 && (
        <section>
          <h2 className={styles.sectionTitle}>Scheduled</h2>
          <ul className={styles.list}>
            {scheduled.map((it, i) => (
              <Row key={`s${i}`} item={it} />
            ))}
          </ul>
        </section>
      )}

      <section>
        <h2 className={styles.sectionTitle}>Open ({openTracked.length})</h2>
        <ul className={styles.list}>
          {openTracked.map((it, i) => (
            <Row key={`o${i}`} item={it} />
          ))}
        </ul>
      </section>

      {done.length > 0 && (
        <section>
          <h2 className={styles.sectionTitle}>Done ({done.length})</h2>
          <ul className={styles.list}>
            {done.map((it, i) => (
              <Row key={`d${i}`} item={it} />
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}
