import type {Meta, StoryObj} from '@storybook/react';
import TodosDashboard from './index';

/**
 * TodosDashboard renders the generated todos-data.json (the site-wide rollup of tracked
 * markdown tasks). It reads the real generated data, so the story reflects the current corpus.
 */
const meta = {
  title: 'Components/TodosDashboard',
  component: TodosDashboard,
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'The /todos experience: a rollup (open/done/tracked/scheduled) + a focused list of ' +
          'the genuinely-tracked todos across the site, from todos-data.json (generated by ' +
          'scripts/generate-todos-data.js via `npm run generate-assets`). "Age" is shown ' +
          'instead of alarmist "overdue" since most due dates are old capture dates.',
      },
    },
  },
  tags: ['autodocs'],
} satisfies Meta<typeof TodosDashboard>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
